name: "Build + Publish NuGet Package"

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "*.sln"

  push:
    branches:
      - master
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "*.sln"

env:
  DOTNET_NOLOGO: true

jobs:
  get-head-commit-message:
    runs-on: "ubuntu-latest"

    outputs:
     head-commit-message: ${{ steps.get-head-commit-details.outputs.head-commit }}

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get Head Commit message
        id: get-head-commit-details
        run: >
          {
            echo 'head-commit<<EOF'
            git log -1 --pretty=%B
            echo EOF
          } >> "$GITHUB_OUTPUT"

  build:
    runs-on: "rbx-local" # Due to local NuGet
    if: ${{ !contains(needs.get-head-commit-message.outputs.head-commit-message, '#!skip-build!#') }}

    needs: get-head-commit-message

    env:
      VersionSuffix: ${{ github.event.pull_request.number && format('pr-{0}-{1}-{2}-preview', github.event.pull_request.number, github.run_number, github.run_attempt) || '' }}

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Build
      - name: Restore NuGet Packages
        run: >-
          dotnet restore

      - name: Build Solution
        run: >-
          dotnet build
          --no-restore
          -c Release

      - name: Run Tests
        run: >-
          dotnet test
          --no-build
          --no-restore
          -c Release

      - name: Pack NuGet Packages
        run: >-
          dotnet pack
          --no-build
          --no-restore
          --output ./dist
          -c Release

      # Finish
      - name: Upload build artifacts
        if: ${{ github.event_name == 'push' }}
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: nuget-packages
          path: |
            ./dist/*.nupkg

  # Upload to NuGet
  upload:
    runs-on: "rbx-local"

    needs: "build"

    if: ${{ github.event_name == 'push' }}

    steps:
      # Setup
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: dist

      - name: Publish NuGet Packages
        run: >-
          dotnet nuget push
          dist/*.nupkg
          --skip-duplicate
          --source ${{ vars.NUGET_SOURCE }}
          --api-key ${{ secrets.NUGET_API_KEY }}

      - name: Clean up
        run: >-
          rm -rf dist
